name: Deploy image

on:
  push:
    tags: [v*]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:11}
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.GCSALE_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.GCSALE_DOCKER_REGISTRY_TOKEN }}
          registry: docker.pkg.github.com
          repository: gcsale/gs-admin-client
          auto_tag: true
      - name: Send event to deploy service
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GCSALE_REPO_ACCESS_READ }}
          repository: de1mos242/little-diary-root
          event-type: gs-admin-client-released
          client-payload: '{"version": "${{ env.RELEASE_VERSION }}"}'